fix/nae-115/failure action response
briebug/ngrx-auto-entity pull request #121
Opened 2020-04-18 14:35 UTC by schuchard

- provide entity/entities to *failure actions
- provide key(s) to DeleteByKeys and DeleteManyByKeys
- update specs
- typing refactors and improvements
- narrows type on reducer from string to `EntityActionTypes`, fix lint error in reducer
- bump lib version

2020-04-18 16:43 UTC, jrista requested changes

2020-04-18 16:43 UTC, jrista commented on projects/ngrx-auto-entity/src/lib/decorators/entity.ts
> +export interface IEntityInfoBase {
Lets call this `IEntityNames`.

2020-04-18 16:44 UTC, jrista commented
Lets squash all the commits for this into one, with a proper commit message as described last night:

```
feat|fix|refactor: <message>

 + Additions
 - Removals
 * Other stuff

<related issues>
```

2020-04-19 13:03 UTC, schuchard commented
ready to go @jrista

2020-04-19 13:54 UTC, schuchard commented
What do you think about extending this pattern to the `Load*` actions and expose the following?

- `LoadFailure` - `key`
- `LoadManyFailure`, `LoadAllFailure` - `criteria`
- `LoadPageFailure` - `page`
- `LoadRangeFailure` - `range`

Another question, should also be passing the criteria in the failure cases as well. There could be identifying information in there as well, but this could be in a later PR?

2020-04-19 15:44 UTC, schuchard commented
Just realized the types are not accurate for the action. `entity`, `entities`, `key`, and `keys` are not coming through no the action type. Need to make a few more changes.

2020-04-19 16:26 UTC, schuchard commented
false alarm, it turns out we need to explicitly type the action to pickup the properties.

```ts
ofEntityType<Customer, CreateFailure<Customer>>
```

2020-04-20 04:50 UTC, jrista commented
> What do you think about extending this pattern to the `Load*` actions and expose the following?
> 
> * `LoadFailure` - `key`
> * `LoadManyFailure`, `LoadAllFailure` - `criteria`
> * `LoadPageFailure` - `page`
> * `LoadRangeFailure` - `range`
> 
> Another question, should we also be passing the criteria in the failure cases as well? There could be identifying information in there as well, but this could be in a later PR?

Yeah, there is no reason we can't thread all the relevant information through the entire chain of actions.

We might as well go ahead and do that. One of the other stories is also to expand our action patterns from a two-stage to a three-stage patern. From Initiaor -> Result to Initiator -> Response -> Result. I guess it is up to you whether you want to make the changes you recommended here, or maybe wait for the three-stage pattern story, and make them when we make that change?

2020-04-20 04:51 UTC, jrista submitted a review, later dismissed

2020-04-21 03:33 UTC, schuchard commented on projects/ngrx-auto-entity/src/lib/decorators/entity.ts
> +export interface IEntityInfoBase {
updated

2020-04-21 05:18 UTC, jrista approved these changes

2020-04-21 05:18 UTC, merged